### PR TITLE
Updates with minor changes to support the spel execution context

### PR DESCRIPTION
**Pull request by lorengordon**

### CODE REVIEW

**Review by ferricoxide — COMMENTED** [review]
Haven't actually tested that the AWS pre-GRUB doesn't require the boot flag be set on the partition hosting the initramfs. I'd want verification that this doesn't break AMI bootability before accepting in this change to DiskSetup.

(f7d3bfa86d71181700eca20f9d3f533cace78cc5)

**Review by ferricoxide — COMMENTED** [review]
Bah... per-commit comment-capability is sucktacular

**Review by ferricoxide — COMMENTED** [review]
I'm good with adding the flag to vgcreate in DiskSetup (2ff22e7c1b27156397a3abdacabe9fc1fd5d3bec)

**Review by ferricoxide — COMMENTED** [review]
This commit (4811240fddeb92087fc6432a0ce86507f3712472) to MkChrootTree looks fine

**Comment by lorengordon** [comment]
Created centos7 and rhel7 AMIs for testing, confirmation is in slack.

**Comment by ferricoxide** [comment]
Thanks for the update. Most of the rest doesn't raise immediate concerns - just want to check the overall impact of these on naked-AMIgen's functionality.

**Pull request merged**
